name: aws-trip
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # git으로부터 코드 다운로드
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Pemission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
